### PR TITLE
Upgrading to PyPy 5.10.

### PR DESCRIPTION
**Pull request by dhermes**
See https://morepypy.blogspot.com/2017/12/pypy27-and-pypy35-v510-dual-release.html

/cc @arigo @benjaminp

### CODE REVIEW

**Comment by refi64** [comment]
Dang, thanks! This new version went completely under my radar. I'll try uploading it later today.

**Comment by dhermes** [comment]
> This new version went completely under my radar.

That's very understandable with a December 25 release. I only noticed because I ran `pyenv install --list | grep pypy` when setting up a new machine.

**Comment by refi64** [comment]
Huh...when I try to run PyPy after installation, I get:

```
rymg1@DEVPC-2 ~ $ pypy
debug: WARNING: Library path not found, using compiled-in sys.path, with
debug: WARNING: sys.prefix = 'c:\\pypy\\buildbot\\pypy-c-jit-win-x86-32\\build'
debug: WARNING: Make sure the pypy binary is kept inside its tree of files.
debug: WARNING: It is ok to create a symlink to it from somewhere else.
debug: OperationError:
debug:  operror-type: ImportError
debug:  operror-value: No module named os
rymg1@DEVPC-2 ~ $
```

**Comment by dhermes** [comment]
@kirbyfan64 I am neither a Windows user nor a PyPy maintainer so can't offer any help.

I've simply sent these PRs based on the official PyPy releases.

**Comment by arigo** [comment]
Works for me.  Can you check with the regular windows command prompt?  And please file an issue at https://bitbucket.org/pypy/pypy/issues?status=new&status=open if you manage to isolate what might cause the problem.

**Pull request merged**
