### PR TITLE
Bring PyPy2 and 3 under one project.

### PR DESCRIPTION
**Pull request by dhermes**
I will either send a new PR to set up AppVeyor or just send a new commit to this PR.

### CODE REVIEW

**Comment by dhermes** [comment]
@kirbyfan64 So are you a fan of just continuing to push to https://chocolatey.org/packages/python.pypy or should we start a new one for `pypy` / `pypy2`? Also, did you want me to add you to https://chocolatey.org/packages/pypy3?

**Comment by dhermes** [comment]
I added an AppVeyor config and amazingly it worked on my first try: https://ci.appveyor.com/project/dhermes/chocolatey-pypy3/build/1.0.17.test-appveyor

So I've added that file here in this PR.

**Comment by dhermes** [comment]
Also, that build has a 6.0.0 build artifact for `python.pypy` so I started the submission process there: https://chocolatey.org/packages/python.pypy/6.0

**Comment by refi64** [comment]
> So are you a fan of just continuing to push to https://chocolatey.org/packages/python.pypy or should we start a new one for `pypy` / `pypy2`?

Hmm...should probably be `pypy2` and `pypy3`, since that's what main PyPy still uses.

**Comment by refi64** [comment]
Outside of that, LGTM :+1:

**Comment by dhermes** [comment]
> Hmm...should probably be `pypy2` and `pypy3`, since that's what main PyPy still uses.

Does it? AFAICT main PyPy uses `pypy` and `pypy3`. We could also ask them?

**Comment by dhermes** [comment]
Merging now, punting discussion to #9.

**Pull request merged**
