### PR TITLE
Upgrading to PyPy 5.9.

### LINKED ISSUE #1: This package is out-of-date.
https://chocolatey.org/packages/python.pypy still points to PyPy 5.4.1, but the [latest][1] PyPy is 5.9.0 (released October 5, 2017)

[1]: https://morepypy.blogspot.com/2017/10/pypy-v59-released-now-supports-pandas.html

### PR DESCRIPTION
**Pull request by dhermes**
See: https://morepypy.blogspot.com/2017/10/pypy-v59-released-now-supports-pandas.html

Fixes #1.

### CODE REVIEW

**Comment by refi64** [comment]
Dang, I forgot about this...thanks!! I'll probably be able to submit a new package tomorrow or Sunday.

**Comment by dhermes** [comment]
Thanks! Is there a link to follow for the package update?

**Comment by refi64** [comment]
@dhermes You can see it [here](https://chocolatey.org/packages/python.pypy/5.9).

**Comment by dhermes** [comment]
w00t!

**Comment by refi64** [comment]
@dhermes FYI it's been approved!

**Pull request merged**
