### PR TITLE
Add dependency for additional SSL ciphers.

### PR DESCRIPTION
**Pull request by ionelmc**
This is a suggestion from choco moderators to fix the automated checks.

### CODE REVIEW

**Review by dhermes — APPROVED** [review]
LGTM

**Comment by dhermes** [comment]
@ionelmc The CI failure seems to be related to the new change, right?

**Comment by ionelmc** [comment]
Looks like that. What a quagmire that is ... choco's automated tests don't always have it (note that pypy3 passed after a couple resubmissions) and appveyor appears to lack permissions to install that?! I'll try to dump some of the logs maybe something can be done.

**Comment by ionelmc** [comment]
So I've resubmitted the previous package and it managed to pass those damn automated checks.

**Pull request closed without merging**
